# Generated by Django 4.2.9 on 2024-02-13 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Remesa',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('numero', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'remesas',
                'managed': False,
            },
        ),
    ]
